### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by ndzamboni** [Zrilla-App/zrilla#1]
- [ ] downvoting
- [ ]  suggested media based on reviews
- [ ]  pooled with alike users
- [ ]  movie clubs
- [ ]  reblogging/sharing
- [ ]  sharing to socials
- [ ]  tagging films
- [ ]  statistics on films
- [ ]  links to imdb
- [ ]  watchlist
- [ ]  creating pages for indie media
- [ ]  top 5 of the week
- [ ]  jumpscare ratings/reviews
- [ ]  rating categories: tension, dread, gore, etc.
